
---
# Source: elasticsearch-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-operator-elasticsearch-operator
  labels:
    app: elasticsearch-operator
    chart: elasticsearch-operator-0.1.7
    release: es-operator
    heritage: Tiller
---
# Source: elasticsearch-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-operator-elasticsearch-operator
  labels:
    app: elasticsearch-operator
    chart: elasticsearch-operator-0.1.7
    release: es-operator
    heritage: Tiller
rules:
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "create", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims", "services", "secrets", "configmaps"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "get", "deletecollection", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["*"]
- apiGroups: ["enterprises.upmc.com"]
  resources: ["elasticsearchclusters"]
  verbs: ["*"]
---
# Source: elasticsearch-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: es-operator-elasticsearch-operator
  labels:
    app: elasticsearch-operator
    chart: elasticsearch-operator-0.1.7
    release: es-operator
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: es-operator-elasticsearch-operator
subjects:
- kind: ServiceAccount
  name: es-operator-elasticsearch-operator
  namespace: logging
---
# Source: elasticsearch-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-operator-elasticsearch-operator
  labels:
    app: elasticsearch-operator
    chart: elasticsearch-operator-0.1.7
    release: es-operator
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: elasticsearch-operator
      release: es-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-operator
        release: es-operator
    spec:
      serviceAccountName: es-operator-elasticsearch-operator
      containers:
      - name: elasticsearch-operator
        image: "upmcenterprises/elasticsearch-operator:0.3.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/sh"]
        args: ["-c", "/usr/local/bin/elasticsearch-operator -initDaemonsetNamespace $(NAMESPACE)"]
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi